# Generated by Django 4.1.4 on 2022-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='age',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
