# Generated by Django 4.1.4 on 2022-12-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userdetails_age_userdetails_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='shift',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shifts'),
        ),
    ]
