# Generated by Django 4.1.4 on 2022-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userdetails_shift_paymentstatus_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
