# Generated by Django 4.1.4 on 2022-12-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdetails_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='weight',
        ),
    ]
